
CREATE OR REPLACE VIEW CATEGORIA AS 
	SELECT
		UFD1."FldValue" AS "IDCATEGORIAERP",
		UFD1."Descr" AS "DESCRICAO",
		0 AS "DCATEGORIAPAI"
	FROM
		CUFD
		INNER JOIN UFD1 on(CUFD."FieldID" = UFD1."FieldID" AND CUFD."TableID" = UFD1."TableID")
	WHERE
		CUFD."TableID" = 'OITM' 
		AND "AliasID" = 'categoria';