
CREATE OR REPLACE VIEW GRUPOPRODUTO AS 
	SELECT
		UFD1."FldValue" AS "IDGRUPOPRODUTOERP",
		0 AS "IDEMPRESAERP",
		UFD1."Descr" AS "DESCRICAO",
		'1' AS "SITUACAO"
	FROM
		CUFD
		INNER JOIN UFD1 on(CUFD."FieldID" = UFD1."FieldID" AND CUFD."TableID" = UFD1."TableID")
	WHERE
		CUFD."TableID" = 'OITM' 
		AND "AliasID" = 'grupo_sustennutri';