CREATE OR REPLACE VIEW ASSFORMAPAGTOCLIENTE_VA AS
SELECT  p.IDPRAZOPAGTOERP || ' - ' || c.IDCLIENTEERP AS "IDASSPRAZOPAGTOCLI
ENTEERP",  p.IDPRAZOPAGTOERP , c.IDCLIENTEERP 
FROM PRAZOPAGTO p,CLIENTE c  ;