  CREATE OR REPLACE VIEW ASSTABPRECOPRODUTO_VA AS
SELECT
		"IDTABPRECOERP" || ' - ' || "IDPRODUTOERP" AS "IDASSTABPRECOPRODUTOERP",
		"IDTABPRECOERP"  AS "IDTABPRECOERP",
		"IDPRODUTOERP"  AS "IDPRODUTOERP",
		"VALOR1" AS "VALOR",
		"VALORMAXIMO" AS "VALORMINIMO",
		"VALORMINIMO" AS "VALORMAXIMO",
		"DESCMAXIMO1" AS "DESCONTOMAXIMO"
	FROM
		"ASSTABPRECOPRODUTO"
  