CREATE OR REPLACE VIEW CIDADES_VA AS
SELECT DISTINCT
	T0."AbsId" AS "IDCIDADE",
	T1."Code" AS "IDESTADO",
	T0."Name" AS "DESCRICAO"
FROM OCNT T0 
INNER JOIN OCST T1 ON T0."State" = T1."Code"
WHERE T0."AbsId" <> 5581;