CREATE OR REPLACE VIEW CLIENTE_VA AS
SELECT
		"IDCLIENTEERP" AS "IDCLIENTEERP",
		"NOME"  AS "NOME",
		"RSOCIAL"  AS "RSOCIAL",
		"ENDERECO"  AS "ENDERECO",
		"NUMERO"  AS "NUMERO",
		"BAIRRO"  AS "BAIRRO",
		"CEP"  AS "CEP",
		"TELEFONE"  AS "TELEFONE",
		'FAX'  AS "FAX",
		"CELULAR"  AS "CELULAR",
		"EMAIL"  AS "EMAIL",
		"OBSCADASTRAL" AS "OBS",
		"DESCONTOMAXIMO" AS "MAXDESCONTOPEDIDO",
		"CNPJCPF" AS "CNPJCPF",
		"IERG" AS "IERG",
		"DATANASCIMENTO"   AS "DATANASCIMENTO",
		null AS "CIDADE",
		null AS "UF",
		null AS "COMPLEMENTO", 
		"IDREGIAOERP" AS "REGIAO",
		"IDATIVIDADEERP" AS "ATIVIDADE",
		'' AS "EXTRA1",
		'' AS "EXTRA2",
		'' AS "EXTRA3",
		"EMAIL"  AS "EMAILNFE",
		"OBSFINANCEIRA"  AS "OBSFINANCEIRA",
		"TIPOCLIENTE" AS "CLIENTE_TIPO"
	FROM
		CLIENTE
		
	
	