--CREATE OR REPLACE VIEW CLIENTE_VA AS
SELECT
		"IDCLIENTEERP" AS "IDCLIENTEERP",
		"NOME"  AS "NOME",
		"RSOCIAL"  AS "RSOCIAL",
		"ENDERECO"  AS "ENDERECO",
		"NUMERO"  AS "NUMERO",
		"BAIRRO"  AS "BAIRRO",
		"CEP"  AS "CEP",
		"TELEFONE"  AS "TELEFONE",
		'FAX'  AS "FAX",
		"CELULAR"  AS "CELULAR",
		"EMAIL"  AS "EMAIL",
		"OBSCADASTRAL" AS "OBS",
		"CNPJCPF" AS "CNPJCPF",
		"IERG" AS "IERG",
		"DATANASCIMENTO"   AS "DATANASCIMENTO",
		"CIDADE" AS "CIDADE",
		"UF" AS "UF",
		"COMPLEMENTO" AS "COMPLEMENTO", 
		"REGIAO" AS "REGIAO",
		"ATIVIDADE" AS "ATIVIDADE",
		'' AS "EXTRA1",
		'' AS "EXTRA2",
		'' AS "EXTRA3",
		"E_Mail"  AS "EMAILNFE",
		''  AS "OBSFINANCEIRA",
		'' AS "CLIENTE_TIPO"
	FROM
		CLIENTE
		
	
	