CREATE OR REPLACE VIEW USUARIO_VA AS
SELECT 
	T0."SlpCode" AS "IDUSUARIOERP",
	T0."SlpName" AS "NOME",
	0 AS "DESCMAXIMOITEM",
	0 AS "DESCMAXIMOPEDIDO"
FROM OSLP T0 
WHERE
	t0."U_Integracao_sovis" = 1