CREATE OR REPLACE VIEW ASSCLIENTEUSUARIO AS 
SELECT
	 OCRD."CardCode"  AS "IDCLIENTEERP",
	 "IDUSUARIOERP" AS "IDUSUARIOERP" 
FROM OCRD INNER JOIN USUARIO ON  OCRD."SlpCode" = USUARIO."IDUSUARIOERP"
WHERE OCRD."CardType" = 'C'AND exists(SELECT 1 FROM CRD8 WHERE OCRD."CardCode" = CRD8."CardCode" AND CRD8."BPLId" in(2,4,11))