CREATE OR REPLACE VIEW ASSFORMAPAGTOEMPRESA AS
SELECT
"IDEMPRESAERP" AS "IDFORMAPAGTOERP",
"IDEMPRESAERP" AS "IDEMPRESAERP",
0 AS "VALORPEDMINIMO",
0 AS "MARGEMMEDIAPEDIDO",
0 AS "VALORPEDMAXIMO",
12 AS "DESMAXIMOPEDIDO",
0 AS "PAGAMENTOONLINE"
FROM FORMAPAGTO  , EMPRESA



SELECT * FROM ASSFORMAPAGTOEMPRESA
