CREATE OR REPLACE VIEW ASSPRAZOPAGTOTABPRECO AS
SELECT 
	c."Code" || '_' || "U_prazo" AS "IDPRAZOPAGTOERP",
	t."IDTABPRECOERP" AS "IDTABPRECOERP"
FROM 
	TABPRECO t
	INNER JOIN OPLN tt ON tt."ListNum" =  t."IDTABPRECOERP"
	INNER JOIN "@COMISSAO" c ON tt."U_tipoComissao" = c."Code"
	INNER JOIN "@CONDICOESFV" cond ON cond."Code" = c."Code"
