

CREATE OR REPLACE VIEW ASSPRAZOPAGTOTABPRECO AS
SELECT 
"IDPRAZOPAGTOERP" AS "IDPRAZOPAGTOERP",
"IDTABPRECOERP" AS "IDTABPRECOERP"
FROM 
PRAZOPAGTO, TABPRECO t 
WHERE ("IDPRAZOPAGTOERP" = -1 AND "IDTABPRECOERP" = 27) OR "IDTABPRECOERP" = 4;