CREATE OR REPLACE VIEW ASSTABPRECOPRODUTO AS 
	SELECT
		ITM1."PriceList"  AS "IDTABPRECOERP",
		ITM1."ItemCode"  AS IDPRODUTOERP,
		"Price" AS "VALOR1",
		"Price" AS "VALORMAXIMO",
		"Price" AS "VALORMINIMO",
		0.00 AS "VALORUNITARIO"
	FROM
		ITM1
	WHERE
		"PriceList" IN (SELECT IDTABPRECOERP FROM TABPRECO t)
		AND "ItemCode" in(SELECT IDPRODUTOERP FROM produto)
		AND "Price" > 0
		

