CREATE OR REPLACE VIEW ASSTABPRECOPRODUTO AS 
SELECT
		ITM1."PriceList"  AS "IDTABPRECOERP",
		ITM1."ItemCode"  AS IDPRODUTOERP,
		"Price" AS "VALOR1",
		"Price" AS "VALORMAXIMO",
		"Price" AS "VALORMINIMO",
		0.00 AS "VALORUNITARIO",
		 12 AS "DESCMAXIMO1" 
	FROM
		ITM1
	WHERE
		"PriceList" IN (SELECT IDTABPRECOERP FROM TABPRECO t)
		AND "ItemCode" in(SELECT IDPRODUTOERP FROM produto)
		AND "Price" > 0
		AND "ItemCode"  IN (SELECT T0."ItemCode" FROM OITM T0 WHERE T0."validFor"  = 'Y') 
		

