CREATE OR REPLACE VIEW ASSTABPRECOUSUARIO AS
SELECT
	t."IDTABPRECOERP",
	us."IDUSUARIOERP"
FROM
	OPLN c
	INNER JOIN TABPRECO t on(c."ListNum" = t."IDTABPRECOERP")
	INNER JOIN "@LIBERAPARA" l on(l."Code" = c."U_tipoComissao")
	LEFT JOIN "ASSUSUARIOEMPRESA" us on(us."IDEMPRESAERP" = l."U_Filial")
UNION ALL
SELECT
	t."IDTABPRECOERP",
	u."IDUSUARIOERP"
FROM
	OPLN c
	INNER JOIN TABPRECO t on(c."ListNum" = t."IDTABPRECOERP")
	INNER JOIN "@LIBERAPARA" l on(l."Code" = c."U_tipoComissao")
	LEFT JOIN "USUARIO" u on(u."IDUSUARIOERP" = l."U_vendedor")