CREATE VIEW SBOGRUPOROVEMA.ASSTABPRECOUSUARIO AS
SELECT
  "IDTABPRECOERP" AS "IDTABPRECOERP",
  "IDUSUARIOERP" AS "IDUSUARIOERP"
 FROM TABPRECO , USUARIO
 WHERE ("IDTABPRECOERP"=27 AND "IDUSUARIOERP" = 58) OR ("IDTABPRECOERP" = 4);