CREATE VIEW SBOGRUPOROVEMA.ASSUSUARIOEMPRESA AS
SELECT "IDUSUARIOERP" AS "IDUSUARIOERP ", 
 rfv."U_filial" AS "IDEMPRESAERP" FROM
USUARIO
INNER JOIN OSLP o ON o."SlpCode"  = USUARIO."IDUSUARIOERP"
INNER JOIN "@RO_FILIAL_LINHA" rfv ON o."U_filial" = rfv."DocEntry";



