CREATE OR REPLACE VIEW GRUPOPRODUTO AS 
	SELECT
		"ItmsGrpCod"  AS "IDGRUPOPRODUTOERP",
		"IDEMPRESAERP" AS "IDEMPRESAERP",
		"ItmsGrpNam"   AS "DESCRICAO",
		'Y' AS "SITUACAO"
	FROM
		OITB,
		EMPRESA
		