-- SBOGRUPOROVEMA.ITEMPEDIDORETORNO source

CREATE VIEW SBOGRUPOROVEMA.ITEMPEDIDORETORNO AS
SELECT 
DISTINCT
RDR1."ItemCode" || '-'|| ORDR."U_id_pedido_forca"  AS "IDITEMPEDIDORETORNOERP",
COALESCE(RDR1."U_id_item_forca",0) AS "IDITEMPEDIDOSOVIS",
(SELECT "ListNum"   FROM OPLN WHERE "ListNum" = 4) AS "IDTABPRECOERP",
ORDR."DocNum" AS "IDPEDIDORETORNOERP",
RDR1."ItemCode" AS "IDPRODUTOERP",
RDR1."ItemCode" AS "IDPRODUTOREFERENCIA",
RDR1."Quantity" AS "QTDE",
COALESCE(NT."Quantity",0)  AS "QTDEFATURADO",
12 AS "DESCONTOPERMITIDO",
RDR1."DiscPrcnt" AS "DESCONTOPRATICADO",
(SELECT "Price"  FROM ITM1 WHERE "PriceList" = 4 AND "ItemCode" = RDR1."ItemCode" ) AS "VALORTABPRECO",
RDR1."PriceBefDi" AS "VALORUNITARIO",
COALESCE(NT."PriceBefDi",0) AS "VALORUNFAT",
RDR1."LineTotal" AS "VALORTOTAL",
COALESCE(NT."LineTotal",0)  AS "VALORTOTALFAT",
0 AS "SALDOGERADO",
0 AS "VALORDIFERENCA",
RDR1."Usage" AS "TIPO",
0 AS "CUSTOPRODUTO",
'N' AS "PACOTE",
'N' AS "IMUTAVEL",
0 AS "IDPACOTE",
0 AS "VALORST",
0 AS "VALORTOTALST", 
'' AS "OBSERVACAO",
0 AS "IDUNIDADEMEDIDAERP",
0 AS "PERCENTUALREAJUST",
0 AS "FATORCONVERSAOESTOQUE",
0 AS"IDTIPOCULTURA",
0 AS "PESO",
0 AS "COMISSAO",
0 AS "INDICERENTABILIDADE"
FROM RDR1 
INNER JOIN ORDR ON RDR1."DocEntry"  = ORDR."DocEntry"
LEFT JOIN INV1 NT ON RDR1."DocEntry" = NT."BaseEntry" AND RDR1."ItemCode" = NT."ItemCode" 
WHERE ORDR."U_id_pedido_forca" IS NOT NULL AND ORDR."U_id_pedido_forca" <> '0'AND RDR1."U_id_item_forca" IS NOT NULL;