-- SBOGRUPOROVEMA.ITEMPEDIDORETORNO source

CREATE OR REPLACE VIEW SBOGRUPOROVEMA.ITEMPEDIDORETORNO AS
SELECT DISTINCT
QUT1."ItemCode" || '-'|| OQUT."U_id_pedido_forca"  AS "IDITEMPEDIDORETORNOERP",
COALESCE(QUT1."U_id_item_forca",0) AS "IDITEMPEDIDOSOVIS",
(SELECT "ListNum"   FROM OPLN WHERE "ListNum" = 4) AS "IDTABPRECOERP",
OQUT."DocNum" AS "IDPEDIDORETORNOERP",
QUT1."ItemCode" AS "IDPRODUTOERP",
QUT1."ItemCode" AS "IDPRODUTOREFERENCIA",
QUT1."Quantity" AS "QTDE",
COALESCE(NT."Quantity",0)  AS "QTDEFATURADO",
12 AS "DESCONTOPERMITIDO",
QUT1."DiscPrcnt" AS "DESCONTOPRATICADO",
(SELECT "Price"  FROM ITM1 WHERE "PriceList" = 4 AND "ItemCode" = QUT1."ItemCode" ) AS "VALORTABPRECO",
QUT1."PriceBefDi" AS "VALORUNITARIO",
COALESCE(NT."PriceBefDi",0) AS "VALORUNFAT",
QUT1."LineTotal" AS "VALORTOTAL",
COALESCE(NT."LineTotal",0)  AS "VALORTOTALFAT",
0 AS "SALDOGERADO",
0 AS "VALORDIFERENCA",
QUT1."Usage" AS "TIPO",
0 AS "CUSTOPRODUTO",
'N' AS "PACOTE",
'N' AS "IMUTAVEL",
0 AS "IDPACOTE",
0 AS "VALORST",
0 AS "VALORTOTALST", 
'' AS "OBSERVACAO",
0 AS "IDUNIDADEMEDIDAERP",
0 AS "PERCENTUALREAJUST",
0 AS "FATORCONVERSAOESTOQUE",
0 AS"IDTIPOCULTURA",
0 AS "PESO",
0 AS "COMISSAO",
0 AS "INDICERENTABILIDADE"
FROM QUT1 
INNER JOIN OQUT ON QUT1."DocEntry"  = OQUT."DocEntry"
LEFT JOIN INV1 NT ON QUT1."DocEntry" = NT."BaseEntry" AND QUT1."ItemCode" = NT."ItemCode" 
WHERE
	OQUT."U_id_pedido_forca" > '0' AND QUT1."U_id_item_forca" IS NOT NULL;



