CREATE VIEW LOGSTATUSWF AS 
	SELECT
		IDSTATUSWFERP AS "IDLOGSTATUSWFERP",
		IDUSUARIOERP,
		IDSTATUSWFERP AS "IDSTATUSWFERP",
		IDPEDIDORETORNOERP AS "UUIDPEDIDO",
		DATAHORA,
		0 AS IDPEDIDORETORNOERP,
		'' AS "SIGLA"
	FROM
		PEDIDORETORNO