CREATE OR replace VIEW LOGSTATUSWF AS 
	SELECT
		IDSTATUSWFERP AS "IDLOGSTATUSWFERP",
		IDUSUARIOERP,
		IDSTATUSWFERP AS "IDSTATUSWFERP",
		UUID AS "UUIDPEDIDO",
		DATAHORA,
		IDPEDIDORETORNOERP AS IDPEDIDORETORNOERP,
		'' AS "SIGLA"
	FROM
		PEDIDORETORNO
	WHERE UUID IS NOT null;