CREATE OR REPLACE VIEW  PEDIDORETORNO AS
SELECT 
DISTINCT
ORDR."DocNum" AS "IDPEDIDORETORNOERP",
ORDR."U_id_pedido_forca" AS "IDPEDIDOSOVIS",
"IDEMPRESAERP" AS"IDEMPRESAERP",
"IDUSUARIOERP" AS "IDUSUARIOERP",
ORDR."CardCode" AS "IDCLIENTEERP",
(SELECT MAX("Usage")  FROM RDR1 WHERE ORDR."DocEntry" = RDR1."DocEntry" )AS "IDTIPOPEDIDOERP",
ORDR."PeyMethod" AS "IDFORMAPAGTOERP",
ORDR."GroupNum" AS "IDPRAZOPAGTOERP",
0 AS "IDTRANSPORTADORAERP",
'' AS "ORDEMCOMPRA",
ORDR."DocDueDate" AS "DATAENTREGA",
OINV."DocDate"   AS "DATAFATURAMENTO",
ORDR."Comments" AS "OBSPEDIDO",
CAST(OINV."Header" AS VARCHAR) AS "OBSNOTA",
ORDR."DocTotal" AS "VALOR",
(SELECT MAX("DiscPrcnt")  FROM RDR1 WHERE ORDR."DocEntry" = RDR1."DocEntry" ) AS "DESCONTO",
ORDR."DocTotal" AS "VALORTOTAL",
OINV."DocTotal" AS "VALORTOTALFAT",
0 AS "SALDOGERADO",
1 AS "STATUSPEDIDO",
CAST(CASE
	WHEN ORDR."DocStatus" = 'O' THEN 'Não Faturado'
	WHEN ORDR."DocStatus" = 'C' AND ORDR.CANCELED = 'Y' THEN 'Cancelado'
	ELSE 'Faturado'
END AS nvarchar )AS "STATUSPEDIDOERP",
0 AS "FOBCIF",
0 AS  "COEFICIENTE",
0 AS "PRAZODIGITADO",
0 AS "VALORST",
0 AS "VALORTOTALST",
0 AS "VALORIPI",
0 AS "VALORTOTALIPI",
ORDR."DocDate" AS "DATAHORA",
'R$' AS "IDMOEDAERP",
0 AS "IDPROPRIEDADEERP",
0 AS "DESCONTOADICIONAL",
0 AS "IDPEDIDORETORNOORIGEMERP",
CAST(CASE
   WHEN ORDR."DocStatus" = 'O' THEN 'Não Faturado'
   WHEN ORDR."DocStatus" = 'C' AND ORDR.CANCELED = 'Y' THEN 'Cancelado'
	ELSE 'Faturado'
END AS nvarchar ) AS "IDSTATUSWFERP",
0 AS "INDICERENTABILIDADE"
FROM ORDR
LEFT JOIN EMPRESA ON "BPLId" = "IDEMPRESAERP"
LEFT JOIN USUARIO ON "SlpCode" = "IDUSUARIOERP"
INNER JOIN RDR1  ON ORDR."DocEntry" = RDR1."DocEntry" 
INNER JOIN INV1 ON RDR1."DocEntry" = INV1."BaseEntry" 
INNER JOIN OINV ON INV1."DocEntry" = OINV."DocEntry" 



SELECT * FROM FORMAPAGTO f 
