CREATE OR REPLACE VIEW PRODUTO AS
SELECT

T0."ItemCode" AS "IDPRODUTOERP",
T0."ItmsGrpCod" AS "IDGRUPOPRODUTOERP",
0 AS "IDSUBGRUPOPRODUTOERP",
0 AS "IDGRADEERP",
0 AS "IDRAMOERP",
0 AS "IDUNIDADEMEDIDAERP",
T0."ItemName" AS "DESCRICAO",
0 AS "CODBARRAS",
T0."SalPackUn" AS "UNDCAIXA",
T0."SWght1Unit" AS "PESO",
T0."SalUnitMsr" AS "UNDMEDIDUNDMEDIDA",
0 AS "EMBALAGEM",
0 AS "PORCTROCA",
0 AS "IPI",
T0."FirmCode" AS "MARCA",
'' AS "REFERENCIA",
0 AS "ESPESSURA",
0 AS"COMPRIMENTO",
0 AS "LARGURA",
0 AS "QTDEVOLUMES",
0 AS "TIPOMEDIDA",
'' AS "COMPLEMENTO",
'' AS "DATAVENCIMENTO",
T0."UserText" AS "OBSERVACAOGERAL",
CASE WHEN T0."validFor" = 'Y' THEN 0 ELSE 1 END AS "OCULTA",
T0."NCMCode" AS "NCM",
'' AS "CST",
T0."CESTCode" AS "CEST",
0 AS "IDCATEGORIAERP",
0 AS "IDLINHAPRODUTOERP",
0 AS"CUBAGEM",
0 AS "IDCLIENTE",
"EMPRESA"."IDEMPRESAERP" AS "IDEMPRESAERP"
FROM OITM T0, EMPRESA WHERE T0."ItemCode"  Like 'PAC%%' 

SELECT * FROM PRODUTO 