ALTER VIEW REGIAO as -- TODO adicionar regiao em cliente
SELECT
	r."Code",
	0 AS "IDEMPRESAERP",
	r."Name" "DESCRICAO",
	1 "SITUACAO",
	0 "REAJUSTECIF",
	0 "REAJUSTEFOB",
	0 "VALORMINIMOFOB",
	0 "VALORMINIMOCIF",
	0 "TICKETMEDIO"
FROM
	"@RO_LOCAIS" r

	
UNION ALL

	SELECT
		'-1',
		0 AS "IDEMPRESAERP",
		'Sem Regiao' "DESCRICAO",
		1 "SITUACAO",
		0 "REAJUSTECIF",
		0 "REAJUSTEFOB",
		0 "VALORMINIMOFOB",
		0 "VALORMINIMOCIF",
		0 "TICKETMEDIO"
	FROM
		DUMMY



