CREATE OR REPLACE VIEW TIPOPEDIDO AS 
		SELECT
			1 AS "IDTIPOPEDIDOERP",
			"IDEMPRESAERP" AS "IDEMPRESAERP",
			'Venda' AS "DESCRICAO",
			0 AS "COLUNAVENDA",
			0 AS "COLUNATROCA",
			0 AS "COLUNABONIFICACAO",
			0 AS "GERAIMPOSTO",
			0 AS "FATURA",
			0 AS "IMPRIME",
			0 AS "NEGATIVAESTOQUELOCAL",
			0 AS "HABILITAORDEMCOMPRA",
			0 AS "SOLICITACONTRASENHA",
			0 AS "SOLICITAMOTIVOTIPOPEDIDO",
			1 AS "SITUACAO",
			'v' AS "TIPO",
			'N' AS "SUBTRAIVALOR"
		FROM
			dummy,
			empresa;
			
		