SELECT 
"DocNum" AS "IDFATURAERP",
"CardCode" AS "IDCLIENTEERP",
"Serial" AS "NUMNF",
"Series" AS "SERIE" ,
"DocDate" AS "DATAEMISSAO",
"SlpCode" AS "IDUSUARIOERP",
"DocTotal" AS "VALORNOTA",
"GroupNum" AS "IDPRAZOPAGTOERP ",
"BPLId" AS "IDEMPRESAERP" 

FROM OINV