-- SBOGRUPOROVEMA.LOGSTATUSWF fonte

CREATE OR REPLACE VIEW LOGSTATUSWF AS
SELECT
	IDPEDIDORETORNOERP AS "IDLOGSTATUSWFERP",
	IDUSUARIOERP,
	p.IDSTATUSWFERP AS "IDSTATUSWFERP",
	o."U_uuid_forca" AS "UUIDPEDIDO",
	p.DATAHORA,
	p.IDPEDIDORETORNOERP AS IDPEDIDORETORNOERP,
	si.sigla AS "SIGLA"
FROM
	PEDIDORETORNO p
	INNER JOIN STATUSWF si ON(si.IDSTATUSWFERP = p.IDSTATUSWFERP)
	INNER JOIN OQUT o ON o."DocNum" = p.IDPEDIDORETORNOERP 
WHERE o."U_uuid_forca" IS NOT NULL
AND p.IDUSUARIOERP IN (SELECT u."IDUSUARIOERP" FROM USUARIO u);