CREATE OR REPLACE VIEW LOGSTATUSWF AS
SELECT
	IDPEDIDORETORNOERP AS "IDLOGSTATUSWFERP",
	IDUSUARIOERP,
	p.IDSTATUSWFERP AS "IDSTATUSWFERP",
	UUID AS "UUIDPEDIDO",
	p.DATAHORA,
	p.IDPEDIDORETORNOERP AS IDPEDIDORETORNOERP,
	si.sigla AS "SIGLA"
FROM
	PEDIDORETORNO p
	INNER JOIN STATUSWF si ON(si.IDSTATUSWFERP = p.IDSTATUSWFERP)
WHERE UUID IS NOT NULL
AND p.IDUSUARIOERP IN (SELECT u."IDUSUARIOERP" FROM USUARIO u);