CREATE OR REPLACE VIEW SALDOCLIENTE AS 
SELECT 
	o."CardCode" AS "IDCLIENTEERP", 
	j."BPLId" AS "IDEMPRESAERP", 
	(O."CreditLine"-o."Balance")  AS "CREDITOLIBERADO", 
	o."Balance"  AS "SALDODEVEDOR", 
	0 AS "LIMITEBONIFICACAO", 
	0 AS "LIMITEBONIFICACAOP"
FROM 
	OCRD o 
INNER JOIN 
	JDT1 j ON J."ContraAct" = o."CardCode" 
WHERE 
	o."CardType" = 'C'
AND 
	j."BPLId" IN (SELECT "IDEMPRESAERP" FROM EMPRESA e)
GROUP BY 
	o."CardCode", j."BPLId",o."Balance",O."CreditLine";