CREATE OR REPLACE VIEW TABPRECO AS
	SELECT
		T0."ListNum" AS "IDTABPRECOERP",
		0 AS "IDEMPRESAERP", 
		T0."ListName" AS "DESCRICAO",
		IFNULL(CAST(T0."ValidTo" AS DATE),'2100-01-01') AS "DATAVALIDADE",
		CASE WHEN T0."ValidFor" = 'Y' THEN 1 ELSE 0 END AS "SITUACAO",
		0 AS "VOLUMEMINIMOPEDIDO",
		0 AS "PORCACRESCFLEX",
		0 AS "COR",
		0 AS "REAJUSTECIFFOB",
		T0."PrimCurr" AS "IDMOEDAERP",
		0 AS "DESCPRODUTOQTDE"
	FROM 
		OPLN T0
	WHERE 
		T0."U_publica_forca" = 1 AND T0."U_tipoComissao" <> '';

