CREATE OR REPLACE VIEW TIPOPEDIDO AS 
			SELECT
			"ID" AS "IDTIPOPEDIDOERP",
			"IDEMPRESAERP" AS "IDEMPRESAERP",
			CASE WHEN "ID" = 9 THEN 'Venda' ELSE 'Venda Futura' END AS "DESCRICAO",
			1 AS "COLUNAVENDA",
			1 AS "COLUNATROCA",
			1 AS "COLUNABONIFICACAO",
			0 AS "GERAIMPOSTO",
			0 AS "FATURA",
			0 AS "IMPRIME",
			0 AS "NEGATIVAESTOQUELOCAL",
			0 AS "HABILITAORDEMCOMPRA",
			0 AS "SOLICITACONTRASENHA",
			0 AS "SOLICITAMOTIVOTIPOPEDIDO",
			1 AS "SITUACAO",
			'V' AS "TIPO",
			'N' AS "SUBTRAIVALOR"
		FROM
			OUSG,
			empresa
		WHERE "ID"  = 9 or  "ID"  = 16
		
		
		


		