CREATE OR REPLACE VIEW  ASSPRODUTOEMPRESA AS
  SELECT
    "IDPRODUTOERP" AS "IDPRODUTOERP",
    "EMPRESA"."IDEMPRESAERP" AS "IDEMPRESAERP",
    0 AS "MUTIPLICADOR",
    0 AS"MULTIPLICADORTROCA"
  FROM PRODUTO, EMPRESA 