name: 'Deployment - Production'

on:
  push:
    # tags:
    #   - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  container:
    runs-on: self-hosted
    container:
      image: python:3.12.3
      env:
        ADDRESS: ${{secrets.ADDRESS}}
        PORT: ${{secrets.PORT}}
        USER: ${{secrets.USER}}
        PASSWORD: ${{secrets.PASSWORD}}
        DATABASENAME: ${{secrets.DATABASENAME}}
        INSTANCENUMBER: ${{secrets.INSTANCENUMBER}}
        CURRENTSCHEMA: ${{secrets.CURRENTSCHEMA}}
    steps:
      - uses: actions/checkout@v3.5.2
      - name: dependencias
        run: |
          pip install hdbcli
          ls -la
      - name: Run Deploymenet
        run: |
          python3 execut.py
  # deployment:
  #   runs-on: self-hosted
  #   # needs: create-image
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #     - name: Install dependencies
  #       run: |
  #         pip install -r requirements.txt
  #     - name: Display Python version
  #       run: python3 -c "import sys; print(sys.version)"
  #     - name: Execute Deployment
  #       run: python3 execut.py
        
        