name: 'Deployment - Production'

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-image:
    runs-on: self-hosted

    steps:
      - name: Create Properties
        run: |
          docker build -t python-hana .
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    container:
      image: python-hana

    steps:
      - name: Check filesystem
        run: ls -la